### ISSUE TITLE
data generation script 

### ISSUE THREAD

**Issue by pzz2011** [twtygqyy/pytorch-SRDenseNet#3]
I used https://github.com/twtygqyy/pytorch-SRResNet/tree/master/data in the README to generate the dataset.

but when I used the generated dataset and the model in the srdensenet.py to run.
python main.py --cuda
I got the RuntimeError: CUDNN_STATUS_BAD_PARAM
It seems that the sizeof input tensor do not match the model

Traceback (most recent call last):
  File "main.py", line 161, in <module>
    main()
  File "main.py", line 94, in main
    train(training_data_loader, optimizer, model, criterion, epoch)
  File "main.py", line 135, in train
    out = model(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pzz/workspace/pytorch-SRDenseNet/srdensenet.py", line 101, in forward
    residual = self.relu(self.lowlevel(x))   ==========> the input tensor is ((32L, 3L, 24L, 24L), while the  
                                                          ==========> required input is (x,1, y, y)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 237, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 41, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_BAD_PARAM

how to modify the data generation script?

**Comment by twtygqyy** [comment]
@pzz2011 I will push the latest update for this repo, please wait one day or two.

**Comment by twtygqyy** [comment]
@pzz2011 The reason of the error is because SRResNet takes RGB images as inputs while the inputs for SRDenseNet are grey-level images. Please refer https://github.com/twtygqyy/pytorch-LapSRN/tree/master/data for data generation.

**Comment by pzz2011** [comment]
I am looking forward to seeing your new push:-)
thanks.

**Comment by pzz2011** [comment]
hm...  it seems that there is something wrong.
the new data generation script will generate data with 3 channels, which the SRDenseNet's first conv layer's inchannel is 1.

**Comment by twtygqyy** [comment]
@pzz2011 haha, my fault, will push the corrected one.
