### ISSUE TITLE
UnicodeDecodeError in torch.load

### ISSUE THREAD

**Issue by xiongdongping** [twtygqyy/pytorch-SRDenseNet#9]
@twtygqyy I have run into trouble while I try to test the code. The error information is listed below. I have checked it but I can't correct it. Please give me some advise, thanks a lot.

D:\ProgramData\Anaconda3\python.exe D:/ProgramData/twt-pytorch-SRDenseNet-master/eval.py

Traceback (most recent call last):
  File "D:/ProgramData/twt-pytorch-SRDenseNet-master/eval.py", line 31, in <module>
    model = torch.load(opt.model)["model"]
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 469, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 918: ordinal not in range(128)

**Comment by stormcoral** [comment]
@twtygqyy

**Comment by imxyu** [comment]
I met the same problem, have you resolved it?
Thank you!
